buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.14'
    }
}

def isApplication = plugins.hasPlugin("com.android.application")

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.2.0')
    implementation("com.google.firebase:firebase-crashlytics")
}

cdvPluginPostBuildExtras.add {
    if (isApplication && project.extensions.findByName('googleServices') == null) {
        apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
        googleServices.disableVersionCheck = true
    }
}

