<#
.SYNOPSIS
    Scaffolds (or refreshes) a thin linked consumer project for OutSystems
    automation, backed by this workspace as the shared baseline.

.DESCRIPTION
    Creates a consumer project at <Target> that uses this workspace (the
    baseline) IN PLACE for all tooling: the 5 MCP servers, the 36 skills,
    the 6 specialist agents, and the 4 workflow commands. Nothing is copied
    from the baseline except the generated agent/command markdown, whose
    workspace-relative paths are rewritten to absolute baseline paths.

    File roles:
      GENERATED  (regenerated by -Refresh):
        opencode.json, .opencode/agent/*.md, .opencode/command/*.md
      TEMPLATED-USER (created once; -Refresh regenerates ONLY if the user
        has not modified them since the last generation, so baseline moves
        and template fixes propagate without clobbering edits):
        AGENTS.md, .gitignore, <AppName>.md
      USER (created once if missing; never touched again):
        OMLs/, open/.gitkeep, docs/.gitkeep

    A manifest (.opencode/link-manifest.json) records the hash of every
    generated/templated file at generation time. -Refresh refuses to
    overwrite a file whose on-disk hash no longer matches (i.e. the user
    edited it) unless -Force is given. Orphaned generated files (removed
    from the baseline) are reported, never deleted.

    Ends with a readiness check (Verify-LinkedProject.ps1) and exits with
    its exit code (0 = READY).

.PARAMETER Target
    Path to the consumer project directory (created if missing).

.PARAMETER AppName
    Application name (used for the <AppName>.md notes file and templates).

.PARAMETER Baseline
    Baseline workspace root. Defaults to this script's parent folder.

.PARAMETER Refresh
    Only regenerate GENERATED + unmodified TEMPLATED-USER files; leave
    everything else untouched.

.PARAMETER Force
    Overwrite files even when they were modified after generation (or exist
    as foreign content). Destructive for local edits - confirm first.

.EXAMPLE
    .\scripts\New-LinkedProject.ps1 -Target "C:\Users\me\Documents\NewAppAutomation" -AppName "NewApp"

.EXAMPLE
    # after baseline agent/command/template changes, or after moving the baseline:
    .\scripts\New-LinkedProject.ps1 -Target "C:\Users\me\Documents\NewAppAutomation" -AppName "NewApp" -Refresh
#>
param(
    [Parameter(Mandatory = $true)][string]$Target,
    [Parameter(Mandatory = $true)][string]$AppName,
    [string]$Baseline,
    [switch]$Refresh,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
if ([string]::IsNullOrWhiteSpace($Baseline)) { $Baseline = Split-Path $PSScriptRoot -Parent }
$Baseline = [System.IO.Path]::GetFullPath($Baseline)
$Target   = [System.IO.Path]::GetFullPath($Target)
$BaselineFwd = $Baseline -replace '\\', '/'
$TargetFwd   = $Target -replace '\\', '/'
# $-escape for use inside regex replacement strings
$BaselineEsc = $BaselineFwd.Replace('$', '$$')

$Mode = if ($Refresh) { "REFRESH" } else { "CREATE" }

# --- 0. Sanity: target vs baseline -------------------------------------------
$normTarget   = $Target.TrimEnd('\', '/')
$normBaseline = $Baseline.TrimEnd('\', '/')
if ($normTarget -eq $normBaseline) {
    Write-Host "ERROR: Target must not be the baseline itself." -ForegroundColor Red; exit 1
}
if ($normTarget.StartsWith($normBaseline + '\')) {
    Write-Host "WARNING: Target is INSIDE the baseline ($Baseline). This works, but keep consumer" -ForegroundColor Yellow
    Write-Host "         projects as siblings of the baseline unless you have a reason." -ForegroundColor Yellow
}

# --- 1. Validate the baseline -------------------------------------------------
$mcpServers = @(
    @{ Name = "outsystems-tools";      Exe = "toolkits\extraction\mcp\outsystems-tools\publish\OutSystemsMcp.exe" },
    @{ Name = "outsystems-logic";      Exe = "toolkits\extraction\mcp\outsystems-logic\publish\OutSystemsMcpLogic.exe" },
    @{ Name = "outsystems-ui";         Exe = "toolkits\extraction\mcp\outsystems-ui\publish\OutSystemsMcpUi.exe" },
    @{ Name = "outsystems-omleditor";  Exe = "toolkits\editor\mcp\outsystems-omleditor\publish\OutSystemsMcpOmlEditor.exe" },
    @{ Name = "outsystems-liveeditor"; Exe = "toolkits\editor\mcp\outsystems-liveeditor\publish\OutSystemsMcpLiveEditor.exe" }
)
$skillDirs = @(
    @{ Path = "toolkits\extraction\.opencode\skills"; Min = 7 },
    @{ Path = "toolkits\editor\.opencode\skills";     Min = 26 },
    @{ Path = "toolkits\html-docs\.opencode\skills";  Min = 1 }
)
$templates = @("opencode.json", "AGENTS.md", "gitignore", "app-notes.md")

$baselineOk = $true
foreach ($srv in $mcpServers) {
    $exe = Join-Path $Baseline $srv.Exe
    if (-not (Test-Path -LiteralPath $exe)) {
        Write-Host "ERROR: baseline exe missing: $exe" -ForegroundColor Red
        Write-Host "       Run '.\scripts\Build-All.ps1' in the baseline first (the consumer cannot build them)." -ForegroundColor Red
        $baselineOk = $false
    }
}
foreach ($sd in $skillDirs) {
    $p = Join-Path $Baseline $sd.Path
    $n = @(Get-ChildItem -LiteralPath $p -Directory -ErrorAction SilentlyContinue | Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName "SKILL.md") }).Count
    if ($n -lt $sd.Min) {
        Write-Host "ERROR: baseline skills folder incomplete: $($sd.Path) (found $n, expected >= $($sd.Min))" -ForegroundColor Red
        $baselineOk = $false
    }
}
foreach ($req in @("AGENTS.md", "Verify-LinkedProject.ps1")) {
    if (-not (Test-Path -LiteralPath (Join-Path (Join-Path $Baseline "scripts") $req)) -and -not (Test-Path -LiteralPath (Join-Path $Baseline $req))) {
        Write-Host "ERROR: baseline missing $req" -ForegroundColor Red; $baselineOk = $false
    }
}
foreach ($t in $templates) {
    if (-not (Test-Path -LiteralPath (Join-Path (Join-Path $PSScriptRoot "templates") $t))) {
        Write-Host "ERROR: scaffold template missing: scripts\templates\$t" -ForegroundColor Red; $baselineOk = $false
    }
}
$srcAgents = @(Get-ChildItem -LiteralPath (Join-Path $Baseline ".opencode\agent") -Filter *.md -ErrorAction SilentlyContinue)
if ($srcAgents.Count -lt 6) { Write-Host "ERROR: baseline .opencode\agent has $($srcAgents.Count) agents, expected 6." -ForegroundColor Red; $baselineOk = $false }
$srcCommands = @(Get-ChildItem -LiteralPath (Join-Path $Baseline ".opencode\command") -Filter *.md -ErrorAction SilentlyContinue)
if ($srcCommands.Count -lt 4) { Write-Host "ERROR: baseline .opencode\command has $($srcCommands.Count) commands, expected 4." -ForegroundColor Red; $baselineOk = $false }
if (-not $baselineOk) { exit 1 }

Write-Host "New-LinkedProject [$Mode]" -ForegroundColor Cyan
Write-Host "  target:   $Target" -ForegroundColor DarkGray
Write-Host "  baseline: $Baseline" -ForegroundColor DarkGray
Write-Host "  app:      $AppName" -ForegroundColor DarkGray

# --- 2. Helpers ----------------------------------------------------------------
function Get-StringHash {
    param([string]$Text)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Text))
        return ([BitConverter]::ToString($bytes) -replace '-', '')
    } finally { $sha.Dispose() }
}

function ConvertTo-ConsumerText {
    # Rewrites baseline workspace-relative paths to absolute baseline paths.
    param([string]$Text)
    $t = $Text
    $t = [regex]::Replace($t, '(?<![\w/.\\-])toolkits/', "${BaselineEsc}/toolkits/")
    $t = [regex]::Replace($t, '(?<![\w/.\\-])references/', "${BaselineEsc}/references/")
    $t = [regex]::Replace($t, '(?<![\w/.\\-])catalog/', "${BaselineEsc}/catalog/")
    $t = [regex]::Replace($t, '(?<![\w/.\\-])scripts/', "${BaselineEsc}/scripts/")
    $t = [regex]::Replace($t, '\.\\scripts\\', ($Baseline.Replace('$', '$$') + '\scripts\'))
    $t = [regex]::Replace($t, '(?<![\w/.\\-])\.opencode/', "${BaselineEsc}/.opencode/")
    $t = [regex]::Replace($t, '(?<![\w/.\\-])opencode\.json', "${BaselineEsc}/opencode.json")
    # semantic phrases that must mean something different in a consumer
    $t = [regex]::Replace($t, 'Consumer root defaults to the active project under `projects/`; ask\s+when\s+ambiguous\.', 'The consumer root is THIS project (the folder you are running in).')
    $t = $t.Replace('`projects/`', 'this project root')
    $t = $t.Replace('You are the OutSystems reference researcher for the Outsystems_Custom workspace.', 'You are the OutSystems reference researcher for the shared Outsystems_Custom baseline toolkit.')
    $t = $t.Replace('You are the toolkit maintenance specialist for the Outsystems_Custom workspace.', 'You are the toolkit maintenance specialist for the shared Outsystems_Custom baseline toolkit (maintenance edits happen there, not in consumer projects).')
    return $t
}

# --- 3. Load existing manifest --------------------------------------------------
$manifestPath = Join-Path $Target ".opencode\link-manifest.json"
$oldManifest = $null
if (Test-Path -LiteralPath $manifestPath) {
    try { $oldManifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json } catch {
        Write-Host "WARNING: existing link-manifest.json is unreadable ($_);
 treating all files as foreign. Use -Force to overwrite." -ForegroundColor Yellow
    }
}
if ($oldManifest -and $oldManifest.appName -and $oldManifest.appName -ne $AppName) {
    Write-Host "WARNING: manifest was generated for app '$($oldManifest.appName)'; notes file for it is preserved untouched." -ForegroundColor Yellow
}

# newManifest: relpath -> @{ hash; role }
$newManifestFiles = @{}
$orphaned = @()
$skipped = 0; $written = 0; $preservedUser = 0

function Write-ManagedFile {
    # Decides whether a GENERATED/TEMPLATED file may be (re)written, based on
    # the manifest hash, then writes it and records the new hash.
    param(
        [string]$RelPath,      # forward-slash relative path from target root
        [string]$Content,      # desired new content
        [string]$Role          # 'generated' | 'userTemplate'
    )
    $abs = Join-Path $Target ($RelPath -replace '/', '\')
    $dir = Split-Path $abs -Parent
    if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    $oldEntry = $null
    if ($oldManifest -and $oldManifest.files -and $oldManifest.files.PSObject.Properties[$RelPath]) {
        $oldEntry = $oldManifest.files.PSObject.Properties[$RelPath].Value
    }

    if (Test-Path -LiteralPath $abs) {
        $disk = [System.IO.File]::ReadAllText($abs)
        $diskHash = Get-StringHash $disk
        if ($oldEntry -and $diskHash -ne $oldEntry.hash) {
            if ($Force) {
                Write-Host "  FORCE-overwrite (modified since generation): $RelPath" -ForegroundColor Yellow
            } else {
                Write-Host "  skip (modified since generation, no -Force): $RelPath" -ForegroundColor DarkYellow
                $script:skipped++
                # carry the OLD hash forward so future refreshes still detect the edit
                $script:newManifestFiles[$RelPath] = @{ hash = $oldEntry.hash; role = $Role }
                return
            }
        } elseif (-not $oldEntry -and $diskHash -ne (Get-StringHash $Content)) {
            if ($Force) {
                Write-Host "  FORCE-overwrite (foreign content): $RelPath" -ForegroundColor Yellow
            } else {
                Write-Host "  skip (exists with foreign content, no -Force): $RelPath" -ForegroundColor DarkYellow
                $script:skipped++
                return
            }
        }
    }
    [System.IO.File]::WriteAllText($abs, $Content)
    Write-Host "  wrote [$Role] $RelPath" -ForegroundColor Gray
    $script:written++
    $script:newManifestFiles[$RelPath] = @{ hash = (Get-StringHash $Content); role = $Role }
}

# --- 4. Ensure target skeleton --------------------------------------------------
foreach ($d in @("OMLs", "open", "docs", ".opencode\agent", ".opencode\command")) {
    $p = Join-Path $Target $d
    if (-not (Test-Path -LiteralPath $p)) {
        New-Item -ItemType Directory -Path $p -Force | Out-Null
        Write-Host "  created dir: $d\" -ForegroundColor Gray
    }
}
$gitkeepOpen = Join-Path $Target "open\.gitkeep"
if (-not (Test-Path -LiteralPath $gitkeepOpen)) { [System.IO.File]::WriteAllText($gitkeepOpen, "") }
$gitkeepDocs = Join-Path $Target "docs\.gitkeep"
if (-not (Test-Path -LiteralPath $gitkeepDocs)) { [System.IO.File]::WriteAllText($gitkeepDocs, "") }

# --- 5. TEMPLATED-USER files -----------------------------------------------------
$tplDir = Join-Path $PSScriptRoot "templates"

$agentsMd = [System.IO.File]::ReadAllText((Join-Path $tplDir "AGENTS.md"))
$agentsMd = $agentsMd.Replace('__APPNAME__', $AppName).Replace('__BASELINE__', $Baseline).Replace('__TARGET__', $Target)
Write-ManagedFile -RelPath "AGENTS.md" -Content $agentsMd -Role "userTemplate"

$gitignore = [System.IO.File]::ReadAllText((Join-Path $tplDir "gitignore"))
Write-ManagedFile -RelPath ".gitignore" -Content $gitignore -Role "userTemplate"

$appNotes = [System.IO.File]::ReadAllText((Join-Path $tplDir "app-notes.md"))
$appNotes = $appNotes.Replace('__APPNAME__', $AppName).Replace('__BASELINE__', $Baseline).Replace('__TARGET__', $Target)
Write-ManagedFile -RelPath "$AppName.md" -Content $appNotes -Role "userTemplate"

# --- 6. GENERATED: opencode.json -------------------------------------------------
$oc = [System.IO.File]::ReadAllText((Join-Path $tplDir "opencode.json"))
$oc = $oc.Replace('__BASELINE__', $BaselineFwd)
Write-ManagedFile -RelPath "opencode.json" -Content $oc -Role "generated"

# --- 7. GENERATED: specialist agents (copied from baseline, path-rewritten) ------
$agentFooter = @"

---

CONSUMER CONTEXT - linked project ${AppName}: you are running inside the consumer
project at $TargetFwd. The shared baseline toolkit lives at $BaselineFwd (the
absolute paths above point into it). Write every output - extraction docs,
generated sites, edited .oml artifacts (under OMLs/) - under $TargetFwd, never
into the baseline. Toolkit maintenance belongs in the baseline workspace, not
here. GENERATED FILE: regenerate with $BaselineFwd/scripts/New-LinkedProject.ps1 -Refresh.
"@
foreach ($f in $srcAgents) {
    $body = ConvertTo-ConsumerText ([System.IO.File]::ReadAllText($f.FullName))
    Write-ManagedFile -RelPath (".opencode/agent/" + $f.Name) -Content ($body + $agentFooter) -Role "generated"
}

# --- 8. GENERATED: workflow commands (copied from baseline, path-rewritten) ------
foreach ($f in $srcCommands) {
    $body = ConvertTo-ConsumerText ([System.IO.File]::ReadAllText($f.FullName))
    Write-ManagedFile -RelPath (".opencode/command/" + $f.Name) -Content $body -Role "generated"
}

# --- 9. Orphan detection ----------------------------------------------------------
if ($oldManifest -and $oldManifest.files) {
    $newPaths = @($newManifestFiles.Keys)
    foreach ($prop in $oldManifest.files.PSObject.Properties) {
        if ($prop.Value.role -eq 'generated' -and $newPaths -notcontains $prop.Name) {
            $orphaned += $prop.Name
        }
    }
    foreach ($o in $orphaned) {
        Write-Host "  ORPHAN (generated file no longer in baseline, left in place): $o" -ForegroundColor Yellow
    }
}

# --- 10. Write manifest ------------------------------------------------------------
$manifestObj = [ordered]@{
    manifestVersion = 1
    generatedBy     = "$BaselineFwd/scripts/New-LinkedProject.ps1"
    baseline        = $BaselineFwd
    appName         = $AppName
    generatedAt     = (Get-Date).ToUniversalTime().ToString("o")
    files           = $newManifestFiles
}
$manifestJson = ConvertTo-Json -InputObject $manifestObj -Depth 6
[System.IO.File]::WriteAllText($manifestPath, $manifestJson)
Write-Host "  wrote manifest: .opencode/link-manifest.json ($($newManifestFiles.Count) files)" -ForegroundColor Gray

# --- 11. Summary + readiness gate ---------------------------------------------------
Write-Host ""
Write-Host "Scaffold complete: $written written, $skipped skipped, $($orphaned.Count) orphan(s)." -ForegroundColor Cyan

Write-Host ""
Write-Host "Readiness check:" -ForegroundColor Cyan
& (Join-Path $PSScriptRoot "Verify-LinkedProject.ps1") -Target $Target -Baseline $Baseline
$verifyExit = $LASTEXITCODE

if ($verifyExit -eq 0) {
    Write-Host ""
    Write-Host "NEXT STEPS" -ForegroundColor Green
    Write-Host "  1. Launch OpenCode Desktop with this folder as working directory:"
    Write-Host "       Start-Process `"$env:LOCALAPPDATA\Programs\@opencode-aidesktop\OpenCode.exe`" -WorkingDirectory `"$Target`"" -ForegroundColor Gray
    Write-Host "  2. Inside opencode: /mcp must show all five outsystems-* servers connected."
    Write-Host "  3. Try: @os-reference <question>, or /extract-module <module name>."
    Write-Host "  4. After baseline agent/command/config changes:"
    Write-Host "       powershell -File `"$Baseline\scripts\New-LinkedProject.ps1`" -Target `"$Target`" -AppName `"$AppName`" -Refresh" -ForegroundColor Gray
}
exit $verifyExit
